### ISSUE TITLE
Remove "TODO" marks in `Sustek-literate-rezani/`

### ISSUE THREAD

**Issue by Witiko** [Witiko/cstug-bulletin-2023-3-4#11]
The two articles in `Sustek-literate-rezani/` are supposed to contain inter-article cross-references, which are currently marked with red "TODO" marks in the articles:

![image](https://github.com/Witiko/cstug-bulletin-2023-3-4/assets/603082/fa92c755-4f96-4340-b507-e36ade9701d4)
![image](https://github.com/Witiko/cstug-bulletin-2023-3-4/assets/603082/29e2fe12-6ef9-4fa7-9510-bccc31339452)
![image](https://github.com/Witiko/cstug-bulletin-2023-3-4/assets/603082/3a5b8834-549f-4746-9a58-282b6b1ae51d)

We should:

- [x] Replace the "TODO" marks with inter-article cross-references.
- [x] Decrement `COLORPAGES` in `Makefile` by 3.
- [x] Remove the cross-references from the bibliography.
