### ISSUE TITLE
Proofread CSTUG Bulletin 2023/3–4

### ISSUE THREAD

**Issue by Witiko** [Witiko/cstug-bulletin-2023-3-4#4]
After issues https://github.com/Witiko/cstug-bulletin-2023-3-4/issues/1 and https://github.com/Witiko/cstug-bulletin-2023-3-4/issues/2 have been closed, send the text of CSTUG Bulletin 2023/3–4 to a proofreader:

- [x] `StaryNovotny-uvodnik/`: Proofread and updated in #30
  - [x] [`StaryNovotny-uvodnik-kor1.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13480521/StaryNovotny-uvodnik-kor1.pdf)
- [x] `StaryNovotny-tug/`: Proofread and updated in #21 and #31
  - [x] [`StaryNovotny-tug-kor1.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13370037/StaryNovotny-tug-kor1.pdf)
  - [x] [`StaryNovotny-tug-rev2.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13431925/StaryNovotny-tug-rev2.pdf)
  - [x] [`StaryNovotny-tug-rev2-kor1.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13480579/StaryNovotny-tug-rev2-kor1.pdf)
- [x] `Sustek-literate-rezani/`: Proofread and updated in https://github.com/Witiko/cstug-bulletin-2023-3-4/pull/28 and https://github.com/Witiko/cstug-bulletin-2023-3-4/pull/35
  - [x] [`Sustek-literate-rezani-kor1.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13468172/Sustek-literate-rezani-kor1.pdf)
  - [x] [`Sustek-literate-rezani-kor2.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13468182/Sustek-literate-rezani-kor2.pdf)
  - [x] [`Sustek-literate-rezani-rev2.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13477800/Sustek-literate-rezani-rev2.pdf)
  - [x] [`Sustek-literate-rezani-rev2-kor2.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13490160/Sustek-literate-rezani-rev2-kor2.pdf)
  - [x] [`Sustek-literate-rezani-rev3.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13490345/Sustek-literate-rezani-rev3.pdf)
- [x] `StaryNovotny-markdown/`: Proofread and updated
- [x] `StaryNovotny-l3seq/`: Proofread and updated
- [x] `Sojka-patterns/` (Czech abstract): Proofread and updated in #33
  - [x] [`Sojka-patterns-abstrakt-kor1.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13468176/Sojka-patterns-abstrakt-kor1.pdf)
  - [x] [`Sojka-patterns-abstrakt-kor2.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13468190/Sojka-patterns-abstrakt-kor2.pdf)
- [x] `Beeton-newbie/`: Proofread and updated in #22 and #32
  - [x] [`Beeton-newbie-kor1.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13370039/Beeton-newbie-kor1.pdf)
  - [x] [`Beeton-newbie-kor2.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13468193/Beeton-newbie-kor2.pdf)
  - [x] [`Beeton-newbie-rev2.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13431928/Beeton-newbie-rev2.pdf)
  - [x] [`Beeton-newbie-rev2-kor1.pdf`](https://github.com/Witiko/cstug-bulletin-2023-3-4/files/13480739/Beeton-newbie-rev2-kor1.pdf)

After #23 has been closed, we should send `Sojka-uvodnik/`, `StaryNovotny-tug/`, `Sustek-literate-rezani/`, and `Beeton-newbie/` to the proofreader for a second reading.

We should receive the proofs on November 27 at the latest and update the articles before November 29.
